### ISSUE TITLE
Renewed certificates persist in metrics

### ISSUE THREAD

**Issue by rdavyd** [joe-elliott/cert-exporter#106]
For example if file on node `/var/lib/kubelet/pki/kubelet.crt` is renewed (deleted and recreated), cert-exporter maintains reference to old certificate in metrics:
![изображение](https://user-images.githubusercontent.com/57534322/172377239-eb8493a9-2b52-45cf-ba0d-ea7e656f5f74.png)
Is it expected behavior?

**Comment by joe-elliott** [comment]
I believe this change was trying to address situations like that:
https://github.com/joe-elliott/cert-exporter/pull/79

**Comment by rdavyd** [comment]
It appears, that I messed with container tag in helm and was using the old version regardless of chart version. Sorry for confusion.
