### ISSUE TITLE
Lifecycle

### ISSUE THREAD

**Issue by sass1997** [joe-elliott/cert-exporter#109]
Hi Joe,

Would it be possible that you can do some lifecycle on the GO side? Upgrade to the latest state etc.
If you agree I will create a PR to upgrade the Dockerfile to the newest status/versions.

**Comment by joe-elliott** [comment]
We recently updated the code to use go 1.18, but I'm sure the Docker base images are out of date. If you took the time to update our docker images (and any other depedencies that make sense) I will cut a new image/helm chart.
