### ISSUE TITLE
Support Multiple -secrets-data-glob

### ISSUE THREAD

**Issue by joe-elliott** [joe-elliott/cert-exporter#12]
Support for multiple -secrets-label-selectors and -secrets-annotation-selectors exist, but not -secrets-data-glob.

How should this work?

- Option 1: Create a way to match up label/annotation selectors with data globs
  - Would be flexible but cause configuration to be overly complex and difficult to understand
- Option 2: Accept multiple secrets data globs.  Add support for -exclude-data-glob and apply the globs to all secrets discovered by the selectors equally.
  - Not as flexible but more straightforward configuration.

I am partial to option 2.  If someone's config needs to be that complicated it would be easy to run multiple cert-exporter's with different combinations of parameters.

@ananth07reddy, @haarchri, you have shown interest in these features in the past.  Feel free to voice an opinion!

**Comment by ananth07reddy** [comment]
Hi,

I would also go with **Option 2**. 

Thank you for your support on this :+1:

**Comment by haarchri** [comment]
Option 2 would be the best for our situation

**Comment by joe-elliott** [comment]
Thanks!  Will try to get to this sometime soon.
