### ISSUE TITLE
Support for pfx format

### ISSUE THREAD

**Issue by EnriqueJoseSanjuaneloRobles-TomTom** [joe-elliott/cert-exporter#123]
Is it possible to add PFX/ PKCS#12 format support? I guess it can be done  using this library https://pkg.go.dev/golang.org/x/crypto/pkcs12 ?

**Comment by joe-elliott** [comment]
I'm not opposed to it. Perhaps if the current decode method fails we attempt to decode using the format you have linked?

A change somewhere in here:
https://github.com/joe-elliott/cert-exporter/blob/master/src/exporters/certHelpers.go#L38

Do you want to take a crack at it?
