### ISSUE TITLE
ARM Docker images

### ISSUE THREAD

**Issue by 95gabor** [joe-elliott/cert-exporter#134]
Cloud you build and publish ARM-based Docker images?

**Comment by joe-elliott** [comment]
This doesn't seem terribly difficult:

https://docs.docker.com/build/ci/github-actions/multi-platform/

Which arm platforms are you wanting to target?

**Comment by joe-elliott** [comment]
@95gabor i believe this is done:

![image](https://github.com/joe-elliott/cert-exporter/assets/2272392/79ef1d17-8c48-4034-b157-19a2bf2fe440)

It should be available in helm chart 3.4.1. Let me know if you have any issues!

**Comment by 95gabor** [comment]
Thank you very much! It is working as expected. 🚀
