### ISSUE TITLE
Does cert-exporter work on Windows?

### ISSUE THREAD

**Issue by WarpedEdge** [joe-elliott/cert-exporter#138]
We are looking into cert-exporter to expose our Linux certs, but I was also asked if it can also pull certs from windows environments as well. The dashboards showing its capability only show Linux and do not see any related issues that have asked about this.

**Comment by joe-elliott** [comment]
- cert-exporter has no special functionality for the windows cert store or other windows specific things
- cert-exporter has no pre-built windows binaries

other than the above, i think you should be able to build cert-exporter for windows and it should work. if it doesn't, let me know

**Comment by WarpedEdge** [comment]
@joe-elliott Thanks for the help. I have not been able to fully test on Windows yet, but I will inform you once I have so that others can know for future use cases.
