### ISSUE TITLE
Exposing paths on servers, missing documentation?

### ISSUE THREAD

**Issue by WarpedEdge** [joe-elliott/cert-exporter#142]
I cannot find any instructions on exposing certificates with the cert-exporter, both kubernetes nodes and non-kubernetes nodes. For example I am trying to expose certs in

~/etc/pki/

These would include .cer, .crt, or .pem files

Looking through the default values, and looking online from your post: https://grafana.com/blog/2020/03/04/pro-tip-how-to-monitor-client-certificate-expirations-with-prometheus/. Please let me know if I am missing some crucial step that may have been overlooked. Thank you for your time.

EDIT: I found in one of the previous issues of using --insert-cert-glob which i added:

- --insert-cert-glob=/etc/pki/*.cer

However, even though it shows in the configs for the deployment via kubernetes yaml, it is not showing the new certs in a prometheus query, nor the path. Any ideas what may be going wrong?

**Comment by sagarmujumale** [comment]
I am having same issue
