### ISSUE TITLE
Recursive glob (**) created a directory

### ISSUE THREAD

**Issue by amarao** [joe-elliott/cert-exporter#148]
If parameter set to recursive glob, (`--include-cert-glob=/tmp/**/*.pem`), it creates a directory `/tmp/**` in a filesystem.

I didn't expect exporter to create any directories at all.

affected version: 2.11.1

(to reproduce it, disable shell globbing: `set -f` before running exporter).

**Comment by amarao** [comment]
Sorry, my bad. Docker did it with volume mounts.

**Comment by joe-elliott** [comment]
No problem :)
