### ISSUE TITLE
Support for Installing cert-exporter as a Windows Service

### ISSUE THREAD

**Issue by esimeon-hc** [joe-elliott/cert-exporter#158]
Hello Team,
Thank you for this great exporter.

I am trying to install cert-exporter as a Windows Service.
Unfortunately, what I thought was going to be trivial setup ends up being a real issue for Go based applications; requiring additional callbacks.

I was checking if anyone had any recommendations or success with tools like: 
https://github.com/kardianos/service

Thank you in advance for your inputs

**Comment by joe-elliott** [comment]
I have not worked on Windows in many years. Have you tried something like this:

https://github.com/winsw/winsw

**Comment by esimeon-hc** [comment]
Thank you @joe-elliott,
I was able to install the service with WinSW.
