### ISSUE TITLE
Can cert-exporter get router and registry cert secret from k8s v1.6(ocp 3.6)?

### ISSUE THREAD

**Issue by hellowordczy** [joe-elliott/cert-exporter#16]
Hello,I try to deploy cert-exporter v1.3.0  to get certificate info from router and registry cert secret in ocp 3.6. In logs or metrics ,I cannot get info about router and registry cert secret in ocp v3.6. I wonder know that cert-export support to get cert secret from ocp v3.6 or kubernetes v1.6.

**Comment by joe-elliott** [comment]
Off the top of my head, I have no idea.

- What do the cert-exporter logs say?
- How is your secret setup? (labels/annotations/data values)
- What CLI parameters are you passing to cert-exporter?
