### ISSUE TITLE
cert-manager.io/v1alpha2 not supported

### ISSUE THREAD

**Issue by ananth07reddy** [joe-elliott/cert-exporter#2]
I have tested Cert-exporter successfully with the node daemonset but not with the cert-manager.
We have been using cert-manager successfully in our cluster to issue and renewal TLS certificates.

I have deployed cert-exporter deployment as here https://github.com/joe-elliott/cert-exporter/blob/master/docs/cert-manager.yaml with the following args:

args:
- --secrets-label-selector=cert-manager.io/certificate-name
- --alsologtostderr

**Note**
We are using **cert-manager.io/v1alpha2** apiVersion for the certificates. So, I have modified the arg to **- --secrets-label-selector=cert-manager.io/certificate-name**

**Logs show as below:**

I0309 14:02:37.901374       1 main.go:47] Application Starting
I0309 14:02:37.911237       1 periodicSecretChecker.go:53] Begin periodic check

I don't see any data using the metric **cert_exporter_secret_expires_in_seconds** in the Prometheus. I think this exporter is not capable of export certs using **cert-manager.io/v1alpha2** apiVersion

Please kindly provide me with suggestions to make it work.

**Comment by joe-elliott** [comment]
So it appears that cert-manager dropped support for adding labels to created secrets: 

https://github.com/jetstack/cert-manager/issues/2265

I have confirmed this by testing locally.  I think the right choice will be to search by annotations which is not directly supported by the k8s api.  i.e. we will pull all secrets and manually filter using annotations.  

I may get a chance to address this in the next couple weeks.  Feel free to submit a PR if you need this sooner.

**Comment by ananth07reddy** [comment]
Thanks for your quick reply. 

I would wait untill your next update on this.
