### ISSUE TITLE
get secrets only from namespace where cert-exporter is running

### ISSUE THREAD

**Issue by haarchri** [joe-elliott/cert-exporter#4]
hello,

we have the situation, that we using a shared cluster and only have rights in our namespace - so we would check our certificates in secrets for ("kubernetes.io/tls") ...
so we created RBAC Rules only for our local namespace but the cert-exporter will get all secrets from cluster-level  - is there a solution only get secrets from specific namespace ?

thanks

**Comment by joe-elliott** [comment]
Fixed by #6
