### ISSUE TITLE
Figure out attaching binaries to a release

### ISSUE THREAD

**Issue by joe-elliott** [joe-elliott/cert-exporter#45]
Currently when pushing a version tag release artifacts are being built correclty:

https://github.com/joe-elliott/cert-exporter/actions/runs/220712419

Figure out the best method of attaching these to a release.

@rgl 
If I attempt to create a release through the github UI there is no option to attach the artifacts of the build to the release.  It seems I'd have to manually download and attach to the release.  Do you know of any automation options here?  Am I missing something obvious?

**Comment by joe-elliott** [comment]
Thanks!  It took a little finagling but I figured it out.

**Comment by rgl** [comment]
Oh it was the workflow trigger after all! Didn't notice that...

**Comment by rgl** [comment]
I confirm its working fine on windows. For me, You can close issue :-)
