### ISSUE TITLE
connection refused :8080/metrics

### ISSUE THREAD

**Issue by haarchri** [joe-elliott/cert-exporter#5]
we facing an issue with the metrics endpoint - any ideas ?

```
/app $ wget localhost:8080/metrics
Connecting to localhost:8080 ([::1]:8080)
wget: can't open 'metrics': Permission denied
```

**Comment by joe-elliott** [comment]
You are attempting to save a file locally that you don't have permission to write.  Try

`wget -qO- localhost:8080/metrics`

**Comment by haarchri** [comment]
yes your are right :D we missed it ...
