### ISSUE TITLE
correct values for grafana

### ISSUE THREAD

**Issue by Nurlan199206** [joe-elliott/cert-exporter#51]
i'm succesfully started cert-exporter service, exporter scraping from pem files

but which unit need to select in grafana for show correct values? because its shows 49 years lol.

**Comment by joe-elliott** [comment]
Are you certain your cert doesn't expire in 49 years?  What is the raw metric value?  If you dump the cert when does it say it expires?

**Comment by Nurlan199206** [comment]
![Снимок экрана 2020-10-16 в 12 09 33](https://user-images.githubusercontent.com/22808731/96219398-91cd3800-0fa8-11eb-8dcc-bf663dcddaf0.png)

**Comment by Nurlan199206** [comment]
![Uploading Снимок экрана 2020-10-16 в 12.13.43.png…]()

**Comment by Nurlan199206** [comment]
![Снимок экрана 2020-10-16 в 12 13 43](https://user-images.githubusercontent.com/22808731/96219968-b5dd4900-0fa9-11eb-8d6a-d292842c1841.png)

**Comment by joe-elliott** [comment]
It looks like you have it.  That cert expires in ~1.8 years which is what your dashboard id showing.

**Comment by Nurlan199206** [comment]
Thank you.
