### ISSUE TITLE
Helm install doesn't work

### ISSUE THREAD

**Issue by hagsfdf** [joe-elliott/cert-exporter#53]
I am trying to install cert-exporter by helm.

- helm version: v3.3.4

Sure that I added the repo. `helm search repo cert-exporter` shows the right exporter. After `helm repo update` and seeing "Successfully got an update from the "cert-exporter" chart repository", `helm install` fails...

With debug flag, I was able to see that 
```
Error: failed to fetch https://github.com/joe-elliott/cert-exporter/releases/download/cert-exporter-0.1.1/cert-exporter-0.1.1.tgz : 404 Not Found
```

I think the url should be https://github.com/joe-elliott/cert-exporter/archive/cert-exporter-0.1.1.tar.gz . It's weird...

**Comment by joe-elliott** [comment]
Oh, it might be because I deleted the release.  I honestly didn't like that feature of the helm releaser b/c it took the place of the current "real" release of cert-exporter on the github main page.

@flipstone42  is there anyway to keep your helm chart releaser process from creating an actual github release?

**Comment by flipstone42** [comment]
@joe-elliott - there probably is. I'll have a look into it and get back to you.

**Comment by hagsfdf** [comment]
I see. But as an end-user, I am eagerly looking forward to it. It would be glad to know when it supports helm chart someday.

**Comment by flipstone42** [comment]
@joe-elliott I'm not sure how GitHub Releases work when it comes to adding multiple artifacts through different actions, but if you give the chart the same version in `Chart.yaml`, that might work. It would be easy enough to test.

**Comment by joe-elliott** [comment]
Ha, I suppose that's an option.  Will try.

**Comment by joe-elliott** [comment]
@hagsfdf see if you can install the 2.3.2 chart

**Comment by hagsfdf** [comment]
Nice! It works. But there's a new emerging error: it produces error in line https://github.com/joe-elliott/cert-exporter/blob/master/helm/cert-exporter/templates/dashboards/dashboard.yml#L391

The error is : 
```
Error: parse error at (cert-exporter/templates/dashboards/dashboard.yml:391): function "kubernetes_pod_name" not defined
```

Want me to raise a separate issue?

**Comment by flipstone42** [comment]
I'll fix this, not sure how this wasn't caught in my testing.

**Comment by hagsfdf** [comment]
Good. May I ask the approximate ETA of helm support(stable version,hopefully) ? I want to apply it in my production cluster. So it's kinda important that when it's gonna be a stable version.

**Comment by joe-elliott** [comment]
@flipstone42 this is my fault.  the dashboard was breaking the hugo parsing when github pages was trying to generate output.  It tripped up on this:

https://github.com/joe-elliott/cert-exporter/commit/ae6e14350a5dacb00d5ad6c5e92b37ab2a3a00f2

Unless you want to fight obscure hugo errors with a long feedback loop do you just want to remove `{{kubernetes_pod_name}}` from that dashboard?

**Comment by flipstone42** [comment]
Thanks for clarifying @joe-elliott. I can't see any Hugo errors in the GitHub Actions logs, could you point me towards them?

**Comment by joe-elliott** [comment]
It doesn't show up in the github action logs.  The github action succeeds but the page never gets published.  The error only shows up in the settings and looks something like this:

https://github.com/wowchemy/wowchemy-hugo-modules/issues/959

**Comment by flipstone42** [comment]
Oh man, that's annoying. Let's just leave remove `{{kubernetes_pod_name}}`.

**Comment by hagsfdf** [comment]
In fact, I'm perfectly fine with removing grafana functionality b/c you already  published grafana json in grafana community dashboard.

**Comment by joe-elliott** [comment]
Ok, I'm not helm wizard, but I just did this:
```
$ helm install cert-exporter/cert-exporter --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/joe/.config/k3d/tns/kubeconfig.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/joe/.config/k3d/tns/kubeconfig.yaml
NAME: cert-exporter-1603827667
LAST DEPLOYED: Tue Oct 27 15:41:08 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Cert-Exporter has now been installed, have fun!
```
@hagsfdf see if things are working for you?

**Comment by hagsfdf** [comment]
Perfectly works! Thx for your hard work, and selling your own soul!
