### ISSUE TITLE
Deleted cert still shows up?

### ISSUE THREAD

**Issue by franklouwers** [joe-elliott/cert-exporter#56]
Hi,

I am a new user of your product, so sorry if I missed something in the docs...

The dashboard alerted me of an expired cert in a secret, which was for an Ingress we don't use anymore. I deleted the secret, and waited for an hour, but it still showed up in the dashboard. When I restarted the pod, it disappeared. Our current `--pollling-period` is set to 15m...

**Comment by joe-elliott** [comment]
Yeah, I think that's a consequence of the way we use the prometheus client.  Unsure if there's an easy way to fix that or not.  If you have any ideas feel free to let us know :).

**Comment by joe-elliott** [comment]
I have not had time to work on this directly for awhile, but am accepting PRs and doing builds. I think the best fix for this might be to recreate the Prometheus registry on every run to reset all metrics.

**Comment by joe-elliott** [comment]
Fixed in #79
