### ISSUE TITLE
Incorrect cert CN

### ISSUE THREAD

**Issue by Arkhipov-Oleg** [joe-elliott/cert-exporter#60]
Certificate CN shows incorrectly when exporter parse crt files.

Here is example:
`
cert_exporter_cert_expires_in_seconds{cn="DigiCert SHA2 Secure Server CA",filename="mycert.crt",instance="localhost:9088",issuer="DigiCert Global Root CA",job="cert-exporter"}
`

**Comment by Arkhipov-Oleg** [comment]
Found that exporter monitoring also previous signer in chain of certs, not only last certificate.
So in prometheus you will probably get 2 records, with your domain CN and Root CA signer for the same ca file.

Close issue.

**Comment by AAFAYZ** [comment]
Hello, @Arkhipov-Oleg and @joe-elliott,

Wanted to know whether the .crt file is separately mounted directly into a pod and used as a certificate? And cert-exporter is able to support to track it?

I have a scenario where there are some certificates that are not a K8s resource or neither direct PEM file. These can be _.crt_ or _.jks_  format files mounted into the pod. Will cert-exporter be able to identify and track it?

**Comment by joe-elliott** [comment]
This is the method used to decode the file bytes:

https://github.com/joe-elliott/cert-exporter/blob/83bce94db3c57c38a446d85718d60d0a376b1d67/src/exporters/certHelpers.go#L43

So anything this supports will work I suppose.
