### ISSUE TITLE
Cert-exporter couldn't be able to extract PEM format certificates 

### ISSUE THREAD

**Issue by ananth07reddy** [joe-elliott/cert-exporter#7]
Cert-exporter working as expected with the '*.crt' format certificates but not with the '*.pem format certificates. Would it be possible to make it work with the PEM format certificates? If this is possible, we can also extract OpenSSL certs metrics from the cluster to track.

**Comment by joe-elliott** [comment]
Is cert-exporter logging an error?  cert-exporter should already support pem files.  Perhaps you just need to add an appropriate cert glob?
```
--include-cert-glob=/path/to/certs/*.pem
```

**Comment by ananth07reddy** [comment]
> Is cert-exporter logging an error? cert-exporter should already support pem files. Perhaps you just need to add an appropriate cert glob?
> 
> ```
> --include-cert-glob=/path/to/certs/*.pem
> ```

Yes. I'm having below error

**Comment by ananth07reddy** [comment]
> > Is cert-exporter logging an error? cert-exporter should already support pem files. Perhaps you just need to add an appropriate cert glob?
> > ```
> > --include-cert-glob=/path/to/certs/*.pem
> > ```
> 
> Yes. I'm having below error

**Error exporting secret Failed to parse as a pem**

**Comment by ananth07reddy** [comment]
This error comes from the cert-exporter deployment which is used to extract from Kubernetes secrets, not from the Node or Master.
> > > Is cert-exporter logging an error? 
yes. It says 'Error exporting secret Failed to parse as a pem'

**Comment by joe-elliott** [comment]
Can you generate a dummy secret that cert-exporter fails on and provide it?  If so I can take a look.

**Comment by ananth07reddy** [comment]
> Can you generate a dummy secret that cert-exporter fails on and provide it? If so I can take a look.

I already have some secrets in my cluster with the *.pem extension. It is failed to parse as a pem with the following log message

E0318 10:20:14.705165       1 periodicSecretChecker.go:114] Error exporting secret Failed to parse as a pem

**Comment by joe-elliott** [comment]
Right, but as far as I can tell the code is written to correctly parse the pem format.  If you can provide a secret that cert-exporter is failing to parse then I can work on a fix.  Obviously you would not want to provide a real secret which is why I suggested generating a dummy one.

**Comment by ananth07reddy** [comment]
> Right, but as far as I can tell the code is written to correctly parse the pem format. If you can provide a secret that cert-exporter is failing to parse then I can work on a fix. Obviously you would not want to provide a real secret which is why I suggested generating a dummy one.

Okay.  I couldn't able to attach the file but anyway I am pasting the certificate data in the below
 
-----BEGIN CERTIFICATE-----
MIIDBzCCAe+gAwIBAgIUL5Q4+4bGE2JIH25vOaLKl6afZbQwDQYJKoZIhvcNAQEL
BQAwEzERMA8GA1UEAwwIaG1zLXRlc3QwHhcNMjAwMzEzMTExNTUzWhcNMjEwMzEz
MTExNTUzWjATMREwDwYDVQQDDAhobXMtdGVzdDCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMUMd89v/Dn3AMEVpph/aDLIXtO4xGYakhr+vD5bwtENi38x
xngYhwZbpaI+NHGfRqVxgA2/QrPHoKPq6xxL+UTkzkaPth+YQRj3yja0nwzSg6Ib
4e2/+yrkbt3oQ+i9J9dgiKlWoVNzrUvSxhFAA2yorQ+zhfoRDtslGlRqd7Bx6+xo
miUJTeSXQXufeYVlR4LJ58ef1GiBySjx1UAzJXlA6zNLUNAxvRlGuXK7AG56eGDk
6LJmDS0zV71PoA3fb/QqSgQvSMwjisw8WYChALPz/NYq+A2p3NuhxrMWDNxMvqSE
JtlrJkvzdfouicj9qz2e3pNeunvmh69QMVtj570CAwEAAaNTMFEwHQYDVR0OBBYE
FJjzYoYtMOjz1dUYRHXIj+B9avSvMB8GA1UdIwQYMBaAFJjzYoYtMOjz1dUYRHXI
j+B9avSvMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJTvD7EF
UwwKKeEaYEzRKH8VjyRwO1E1d7q0UxC9Onl/fLu4/DXSm/L+om+yAk+WjsUkf6Gs
VutNlmCD0Nqee5FsVc/6FyaAFRPn9Q2e53pPDPMRpIh0ttdqwPuY7QHj1AErQkF+
0/Y8WhNYkA+rTTypmta0xuu+sBW1DkD9bz/GQjjfnvSL2U2H3fu/KrpDP3tJocm4
Ps0Xgoo+i6CBFct8tKPak+e5MHkrMvU4vMWT5i9J75iYDwGPdeioJQ74YRIz4Ij5
gUoujzeH7Mj+qi59tTu7nuQdyUxHpGxeRRkFd/dUjmumd5Lm2SobCH6hyuAlukD/
X2VNb41zyF/0k04=
-----END CERTIFICATE-----

**Comment by joe-elliott** [comment]
I was able to parse the above cert in a k8s secret by saving the contents above to `test.pem` and doing the following:

```
$ openssl x509 -in test.pem -test
Certificate:
  Data:
      Version: 3 (0x2)
      Serial Number:
          2f:94:38:fb:86:c6:13:62:48:1f:6e:6f:39:a2:ca:97:a6:9f:65:b4
      Signature Algorithm: sha256WithRSAEncryption
      Issuer: CN = hms-test
      Validity
          Not Before: Mar 13 11:15:53 2020 GMT
          Not After : Mar 13 11:15:53 2021 GMT
      Subject: CN = hms-test

$ kc create secret generic test --from-file=test.pem`
$ kc annotate secret test test=test

$ go run ../../main.go --kubeconfig=$KUBECONFIG --secrets-namespace 'default' --secrets-annotation-selector=test --secrets-data-glob=*.pem  --alsologtostderr
I0319 11:20:26.229699   10713 main.go:52] Application Starting
I0319 11:20:26.231067   10713 periodicSecretChecker.go:58] Begin periodic check
I0319 11:20:26.240060   10713 periodicSecretChecker.go:88] Reviewing secret default-token-7z64j in default
I0319 11:20:26.240070   10713 periodicSecretChecker.go:88] Reviewing secret test in default
I0319 11:20:26.240076   10713 periodicSecretChecker.go:97] Annotations matched.  Parsing Secret.

$ curl --silent http://localhost:8080/metrics | grep cert
# HELP cert_exporter_error_total Cert Exporter Errors
# TYPE cert_exporter_error_total counter
cert_exporter_error_total 0
# HELP cert_exporter_secret_expires_in_seconds Number of seconds til the cert in the secret 
expires.
# TYPE cert_exporter_secret_expires_in_seconds gauge
cert_exporter_secret_expires_in_seconds{key_name="test.pem",secret_name="test",secret_namespace="default"} 3.1002861224445775e+07
# HELP cert_exporter_secret_not_after_timestamp Expiration timestamp for cert in the secret.
# TYPE cert_exporter_secret_not_after_timestamp gauge
cert_exporter_secret_not_after_timestamp{key_name="test.pem",secret_name="test",secret_namespace="default"} 1.615634153e+09
```

**Comment by ananth07reddy** [comment]
Thank you very much.

Would it be possible to select two annotations values with  **--secrets-annotation-selector**? For example **--secrets-annotation-selector=test** **--secrets-annotation-selector=test2**

I have tried to place two annotations but I've successfully parsed only one annotation.

**Comment by joe-elliott** [comment]
Yeah, it only supports one `--secret-annotation-selector` now.  Certainly possible to add multiple.

If this issue is resolved can you close it and make a new one requesting the feature?
