### ISSUE TITLE
secrets-annotation-selector does't support multiple values

### ISSUE THREAD

**Issue by ananth07reddy** [joe-elliott/cert-exporter#8]
Would it be possible to select two annotations values with --secrets-annotation-selector? For example --secrets-annotation-selector=test --secrets-annotation-selector=test2

#feature request

**Comment by haarchri** [comment]
yes this would great ;)

**Comment by joe-elliott** [comment]
Yup, will try to get to this soon.

**Comment by ananth07reddy** [comment]
Thanks for your work. 

But here comes the new problem that what if my selector arguments are different from each other. Let's say one is **--secrets-annotation-selector='cert-manager.io/certificate-name'** which parses ***.crt** certificates and another is **--secres-annotation-selector=test** which parses ***.pem** certificate. Here I could only match one type of annotaion format because of default **-secrets-data-glob** is ***.crt.** 

Any idea to parse different cert extensions in the one deployment?

Thanks.

**Comment by joe-elliott** [comment]
What do you think?  Is it sufficient to just support multiple `-secrets-data-glob` and if any match then parse as a pem?  

Or do we need something more advanced like a way to match annotation selectors and data globs?
