### ISSUE TITLE
arm builds to run the exporter in AWS graviton 

### ISSUE THREAD

**Issue by infa-kparida** [joe-elliott/cert-exporter#98]
@joe-elliott:  Our infrastructure is moving to get the benefit of ARM based  AWS Graviton.We have been using this exporter in all our environments but it does not work due to different architecture. 

Is it possible to build this exporter for arm please?

armv7 and arm64

**Comment by infa-nandhap** [comment]
@joe-elliott 
is it possible to merge the PR and make a new release?
I don't see ARM builds in docker hub
